graphics.off()
electric=read.table("household_power_consumption.txt",sep=";",head=TRUE)
electric$Date=as.Date(strptime(electric$Date,format="%d/%m/%Y"))
electricity=subset(electric,electric$Date>="2007-02-01"&electric$Date<="2007-02-02")
electricity$Date=paste(as.character(electricity$Date)," ",as.character(electricity$Time))
electricity$Date=strptime(electricity$Date, format="%Y-%m-%d  %H:%M:%S")
electricity$Global_active_power=as.numeric(as.character(electricity$Global_active_power))
par(bg="white")
plot(electricity$Date,electricity$Global_active_power,type='l',ylab="Global Active Power (kilowats)",xlab="")
dev.copy(png, filename = "plot2.png",width=480,height=480,unit="px")
dev.off()
graphics.off()