graphics.off()
electric=read.table("household_power_consumption.txt",sep=";",head=TRUE)
electric$Date=as.Date(strptime(electric$Date,format="%d/%m/%Y"))
electricity=subset(electric,electric$Date>="2007-02-01"&electric$Date<="2007-02-02")
electricity$Global_active_power=as.numeric(as.character(electricity$Global_active_power))
par(bg="white")
hist(electricity$Global_active_power, col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.copy(png, filename = "plot1.png",width=480,height=480,unit="px")
dev.off()
graphics.off()